(function () {
  var T = {
    en: {
      // nav
      'nav.welcome': 'Welcome',
      'nav.boat': 'Boat',
      'nav.upgrades': 'Upgrades',
      'nav.book': 'Book on Airbnb ↗',
      // footer
      'footer.sub': 'Nynäshamn, Stockholm Archipelago',
      'footer.book': 'Book on Airbnb ↗',

      // ── index ─────────────────────────────────────────────────────
      'idx.hero.eyebrow': 'Nynäshamn · Stockholm Archipelago',
      'idx.hero.h1': 'Welcome to<br>Degerholmen',
      'idx.hero.p': 'A secluded summer retreat on a small island — tucked away in the Stockholm archipelago, surrounded by calm water and untouched nature.',
      'idx.hero.cta': 'View Listing on Airbnb ↗',

      'idx.arrival.h2': 'Getting Here',
      'idx.arrival.sub': 'Everything you need for a smooth arrival.',
      'idx.checkin.h3': 'Check-in',
      'idx.checkin.p': 'Check-in is at <strong class="text-stone-800">15:00</strong>. Head to the dock for boat transfer to the island.',
      'idx.parking.h3': 'Parking',
      'idx.parking.p': 'Your designated lot is marked <strong class="text-stone-800">1:14</strong>. Please park as close to the right as possible — there is space for two cars parked one behind the other, nose-in. This keeps the space clear for everyone. If you have any trouble finding the lot, don\'t hesitate to contact us.',

      'idx.water.h2': 'On The Water',
      'idx.water.sub': 'A motorboat is included. Upgrades are available to make the most of the archipelago.',
      'idx.boat.eyebrow': 'Included with your stay',
      'idx.boat.p': '9.9hp Mercury · 6 passengers · no licence needed',
      'idx.boat.cta': 'View boat guide →',
      'idx.up.eyebrow': 'Optional add-on',
      'idx.up.p': 'Finnmaster 50hp · kayak rentals · from €60/week',
      'idx.up.cta': 'View upgrades →',

      'idx.fac.h2': 'Facilities',
      'idx.fac.sub': 'How things work at the property.',
      'idx.wifi.h3': 'Wi-Fi',
      'idx.wifi.p': 'Network: <strong class="text-stone-700">Degis</strong>. Password given at check-in.',
      'idx.wellwater.h3': 'Well Water',
      'idx.wellwater.p': 'The property has its own well providing fresh, clean water that is regularly tested and safe to drink. Being on an island with limited resources, we kindly ask you to conserve water where possible — take shorter showers, turn off the tap while brushing your teeth, and promptly report any leaks.',
      'idx.climate.h3': 'Heating &amp; Cooling',
      'idx.climate.p': 'The house has a heat pump system providing both heating and air conditioning year-round, controlled via remote. The wall radiators are reserved for winter use only.',
      'idx.sauna.h3': 'Wood Sauna',
      'idx.sauna.p': 'Use <strong class="text-stone-700">fresh tap water only</strong> for creating steam — never seawater. Salt damages the stove and affects its functionality. Firewood is stocked by the green shed and ready for use.',
      'idx.trash.h3': 'Trash &amp; Recycling',
      'idx.trash.p': 'The bin is located behind the parking lot and is locked to prevent wildlife from accessing it. Use the <strong class="text-stone-700">blue keychain</strong> to unlock it. Proper disposal helps keep the island clean and beautiful. If you have any questions about recycling, feel free to reach out.',
      'idx.laundry.h3': 'Washing Machine',
      'idx.laundry.p': 'A washing machine is available for your use. As water is a limited resource on the island, please limit use to a few cycles per week.',
      'idx.safety.h3': 'Safety',
      'idx.safety.p': 'Fire alarms, extinguishers, fire blankets &amp; first aid kits throughout.',
      'idx.safety.emg': 'Emergency: 112',

      'idx.toilet.h2': 'Toilet',
      'idx.toilet.sub': 'The Cinderella incineration toilet — eco-friendly and clean. Just follow these steps.',
      'idx.t1.h3': 'Place the filter paper',
      'idx.t1.p': 'Before each use, place a filter paper in the bowl — this is essential for the incineration process to work correctly.',
      'idx.t2.h3': 'Use the toilet',
      'idx.t2.p': 'For number two with minimal waste, add a couple of cups of water to the filter paper first so the flush works properly.',
      'idx.t3.h3': 'Close lid &amp; press start',
      'idx.t3.p': 'Close the lid and press start. Incineration runs automatically — no need to wait.',
      'idx.tp1.h3': 'Just need to pee?',
      'idx.tp1.p': 'Going in the forest is perfectly fine — and it helps preserve toilet capacity.',
      'idx.tp2.h3': 'Stuck filter?',
      'idx.tp2.p': 'Place a new filter on top, add ~0.5 litres of water, and flush again.',

      'idx.more.h2': 'More to Explore',
      'idx.more.sub': 'Swimming, paddling, and sightseeing — there\'s plenty to keep you busy.',
      'idx.swim.h3': 'Swimming',
      'idx.swim.p': 'The best swimming spot is between the ladder and the boat dock, where the water is deep and calm. A great place to cool off on a warm summer day.',
      'idx.sup.h3': 'SUP Board',
      'idx.sup.p': 'Stand-up paddleboard included at no extra cost.',
      'idx.sight.h3': 'Sightseeing &amp; Shopping',
      'idx.sight.p': 'We\'ve curated a Google Map with our favourite points of interest around Nynäshamn — restaurants, swimming spots, sights and more. Feel free to reach out with any questions or suggestions. ↗',

      // ── boat ──────────────────────────────────────────────────────
      'boat.back': '← Back to Welcome',
      'boat.eyebrow': 'Included with your stay',
      'boat.hero.p': 'A small orange motorboat for six, powered by a 9.9hp Mercury engine — your gateway to the archipelago. No licence required under Swedish law.',
      'boat.stat1.label': 'Passengers max',
      'boat.stat2.label': 'Mercury outboard engine',
      'boat.stat3.val': 'No licence',
      'boat.stat3.label': 'Required under Swedish law',
      'boat.gs.h2': 'Getting Started',
      'boat.gs.sub': 'Basic instructions are given at check-in. Keep these in mind while out on the water.',
      'boat.op.h3': 'Operating the Boat',
      'boat.op1': 'Operators must have prior boating experience and basic maritime knowledge.',
      'boat.op2': 'The archipelago has shallow spots and submerged rocks — always use a navigation app. We recommend <strong class="font-semibold text-stone-800">Skippo</strong>, which is free for basic use.',
      'boat.op3': 'Observe all speed limits and designated boating areas.',
      'boat.au.h3': 'After Use',
      'boat.au1': 'Return the boat to its original location and secure it properly.',
      'boat.au2': 'Verify all equipment is accounted for.',
      'boat.au3': 'Report any damage immediately.',
      'boat.safe.h2': 'Safety Rules',
      'boat.lj.h3': 'Life Jackets — Mandatory',
      'boat.lj.p': 'All persons on the motorboat must wear a lifejacket at all times. Life jackets are stored in the dock storage box.',
      'boat.child.h3': 'Children',
      'boat.child.p': 'Adult supervision is required for children at all times on the boat.',
      'boat.alc.h3': 'Alcohol &amp; Drugs',
      'boat.alc.p': 'Operating the boat under the influence of alcohol or drugs is prohibited under Swedish maritime law.',
      'boat.fuel.h2': 'Fuel Policy',
      'boat.tanks.h3': 'Tanks',
      'boat.tank1': '25-litre internal tank — provided <strong class="text-stone-800">fully fuelled</strong>.',
      'boat.tank2': '5-litre emergency tank on board.',
      'boat.tank3': 'Extra fuel will be supplied if needed.',
      'boat.refuel.h3': 'Refuelling',
      'boat.refuel.p': 'The boat must be returned <strong class="text-stone-800">fully fuelled</strong>. Fuel costs <strong class="text-stone-800">€2.50 / litre</strong>, payable via:',
      'boat.pay1': 'PayPal',
      'boat.pay2': 'Revolut',
      'boat.pay3': 'Bank transfer',
      'boat.refuel.note': 'Guests are responsible for any damage caused by improper refuelling.',
      'boat.up.eyebrow': 'Optional upgrade',
      'boat.up.h3': 'Want more power?',
      'boat.up.p': 'Finnmaster 4900CTX · 50hp · 27–30 knots · GPS chart plotter',
      'boat.up.btn': 'View Upgrades →',

      // ── upgrades ──────────────────────────────────────────────────
      'up.back': '← Back to Welcome',
      'up.eyebrow': 'Optional add-ons',
      'up.h1': 'Upgrades',
      'up.hero.p': 'Take your stay to the next level — a premium motorboat or kayaks to explore the archipelago on your own terms.',
      'up.fm.badge': 'Premium upgrade',
      'up.fm.h2': 'Finnmaster 4900CTX',
      'up.fm.p': 'A serious step up from Tangerine Dream. Built for island hopping, fishing, and full-speed day trips across the archipelago.',
      'up.fm.s1.label': 'Selva engine · unleaded 95',
      'up.fm.s2.label': 'Max speed',
      'up.fm.s3.label': 'Length · fits 6 people',
      'up.fm.s4.label': 'Chart plotter included',
      'up.fm.inc.h3': "What's Included",
      'up.fm.i1': 'Deep V-hull — smooth in choppy conditions',
      'up.fm.i2': 'Electric ignition with safety kill-switch',
      'up.fm.i3': 'Storage compartments &amp; swim ladder',
      'up.fm.i4': 'Cushioned seating for 6',
      'up.fm.i5': 'Life jackets (all sizes)',
      'up.fm.i6': 'Paddle, anchor &amp; 25-litre fuel tank',
      'up.fm.i7': 'Full safety briefing',
      'up.fm.note': '<strong class="text-stone-700">Perfect for:</strong> island hopping, grocery runs, swimming spots, fishing, and day trips.',
      'up.fm.price.h3': 'Pricing',
      'up.kayak.h2': 'Kayak Rental',
      'up.kayak.p': 'Two Seabird Discovery kayaks — lightweight, stable, and perfect for exploring the coastline at your own pace.',
      'up.kayak.inc.h3': "What's Included",
      'up.kayak.i1': 'Life vests',
      'up.kayak.i2': 'Paddles',
      'up.kayak.i3': 'Spray skirts',
      'up.kayak.i4': 'Suitable for all skill levels',
      'up.kayak.res': 'Advance reservation recommended — contact us to book.',
      'up.kayak.price.h3': 'Pricing',
      'up.kayak.p1.name': 'Single kayak',
      'up.kayak.p1.sub': 'Per week',
      'up.kayak.p2.name': 'Both kayaks',
      'up.kayak.p2.sub': 'Per week · best value',
    },

    de: {
      // nav
      'nav.welcome': 'Willkommen',
      'nav.boat': 'Boot',
      'nav.upgrades': 'Upgrades',
      'nav.book': 'Auf Airbnb buchen ↗',
      // footer
      'footer.sub': 'Nynäshamn, Stockholmer Schärengarten',
      'footer.book': 'Auf Airbnb buchen ↗',

      // ── index ─────────────────────────────────────────────────────
      'idx.hero.eyebrow': 'Nynäshamn · Stockholmer Schärengarten',
      'idx.hero.h1': 'Willkommen auf<br>Degerholmen',
      'idx.hero.p': 'Ein abgeschiedenes Sommerdomizil auf einer kleinen Insel — eingebettet in den Stockholmer Schärengarten, umgeben von ruhigem Wasser und unberührter Natur.',
      'idx.hero.cta': 'Auf Airbnb ansehen ↗',

      'idx.arrival.h2': 'Anreise',
      'idx.arrival.sub': 'Alles für eine reibungslose Ankunft.',
      'idx.checkin.h3': 'Check-in',
      'idx.checkin.p': 'Check-in ist um <strong class="text-stone-800">15:00 Uhr</strong>. Fahren Sie zum Steg für den Bootstransfer zur Insel.',
      'idx.parking.h3': 'Parken',
      'idx.parking.p': 'Ihr Parkplatz ist mit <strong class="text-stone-800">1:14</strong> markiert. Bitte so weit rechts wie möglich einparken — es ist Platz für zwei Fahrzeuge hintereinander, vorwärts eingeparkt. So bleibt der Platz für alle frei. Bei Schwierigkeiten beim Finden kontaktieren Sie uns bitte.',

      'idx.water.h2': 'Auf dem Wasser',
      'idx.water.sub': 'Ein Motorboot ist inklusive. Upgrades sind verfügbar, um das Beste aus dem Schärengarten herauszuholen.',
      'idx.boat.eyebrow': 'Im Aufenthalt inbegriffen',
      'idx.boat.p': '9,9 PS Mercury · 6 Personen · kein Führerschein erforderlich',
      'idx.boat.cta': 'Zum Boot-Guide →',
      'idx.up.eyebrow': 'Optionales Extra',
      'idx.up.p': 'Finnmaster 50 PS · Kajakverleih · ab 60 €/Woche',
      'idx.up.cta': 'Upgrades ansehen →',

      'idx.fac.h2': 'Ausstattung',
      'idx.fac.sub': 'So funktionieren die Dinge auf dem Anwesen.',
      'idx.wifi.h3': 'WLAN',
      'idx.wifi.p': 'Netzwerk: <strong class="text-stone-700">Degis</strong>. Passwort erhalten Sie beim Check-in.',
      'idx.wellwater.h3': 'Brunnenwasser',
      'idx.wellwater.p': 'Das Haus verfügt über einen eigenen Brunnen mit frischem, regelmäßig geprüftem Wasser, das bedenkenlos getrunken werden kann. Da wir uns auf einer Insel mit begrenzten Ressourcen befinden, bitten wir Sie, Wasser zu sparen — duschen Sie kürzer, lassen Sie den Hahn beim Zähneputzen nicht laufen und melden Sie Lecks umgehend.',
      'idx.climate.h3': 'Heizung &amp; Kühlung',
      'idx.climate.p': 'Das Haus ist mit einer Wärmepumpe ausgestattet, die ganzjährig Heizen und Kühlen ermöglicht, gesteuert per Fernbedienung. Die Wandheizkörper sind nur für den Winterbetrieb vorgesehen.',
      'idx.sauna.h3': 'Holzsauna',
      'idx.sauna.p': 'Bitte ausschließlich <strong class="text-stone-700">frisches Leitungswasser</strong> zum Aufgießen verwenden — niemals Salzwasser. Salz beschädigt den Ofen. Brennholz finden Sie beim grünen Schuppen.',
      'idx.trash.h3': 'Müll &amp; Recycling',
      'idx.trash.p': 'Der Mülleimer befindet sich hinter dem Parkplatz und ist abgeschlossen, um Wildtiere fernzuhalten. Verwenden Sie den <strong class="text-stone-700">blauen Schlüsselbund</strong> zum Öffnen. Korrektes Entsorgen hilft, die Insel sauber zu halten. Bei Fragen zum Recycling wenden Sie sich gerne an uns.',
      'idx.laundry.h3': 'Waschmaschine',
      'idx.laundry.p': 'Eine Waschmaschine steht zur Verfügung. Da Wasser auf der Insel eine begrenzte Ressource ist, bitten wir Sie, die Nutzung auf wenige Waschgänge pro Woche zu beschränken.',
      'idx.safety.h3': 'Sicherheit',
      'idx.safety.p': 'Rauchmelder, Feuerlöscher, Löschdecken &amp; Erste-Hilfe-Kästen sind überall auf dem Anwesen vorhanden.',
      'idx.safety.emg': 'Notruf: 112',

      'idx.toilet.h2': 'Toilette',
      'idx.toilet.sub': 'Die Cinderella-Verbrennungstoilette — umweltfreundlich und sauber. Bitte folgen Sie diesen Schritten.',
      'idx.t1.h3': 'Filterpapier einlegen',
      'idx.t1.p': 'Vor jeder Nutzung ein Filterpapier in die Schüssel legen — das ist entscheidend für den korrekten Verbrennungsprozess.',
      'idx.t2.h3': 'Toilette benutzen',
      'idx.t2.p': 'Bei geringer Menge bitte vorher etwas Wasser auf das Filterpapier geben, damit die Spülung einwandfrei funktioniert.',
      'idx.t3.h3': 'Deckel schließen &amp; Start drücken',
      'idx.t3.p': 'Deckel schließen und Start drücken. Die Verbrennung läuft automatisch — Sie müssen nicht warten.',
      'idx.tp1.h3': 'Nur urinieren?',
      'idx.tp1.p': 'In den Wald gehen ist völlig in Ordnung — und schont die Kapazität der Toilette.',
      'idx.tp2.h3': 'Filterpapier klemmt?',
      'idx.tp2.p': 'Einfach ein neues Filterpapier darauflegen, ca. 0,5 Liter Wasser hinzufügen und erneut spülen.',

      'idx.more.h2': 'Weitere Aktivitäten',
      'idx.more.sub': 'Schwimmen, Paddeln und Sightseeing — es gibt viel zu entdecken.',
      'idx.swim.h3': 'Schwimmen',
      'idx.swim.p': 'Die beste Badestelle befindet sich zwischen der Leiter und dem Bootssteg, wo das Wasser tief und ruhig ist — ideal zum Abkühlen an warmen Sommertagen.',
      'idx.sup.h3': 'SUP-Board',
      'idx.sup.p': 'Stand-up-Paddleboard kostenlos inklusive.',
      'idx.sight.h3': 'Sehenswürdigkeiten &amp; Einkaufen',
      'idx.sight.p': 'Wir haben eine Google Maps-Karte mit unseren liebsten Sehenswürdigkeiten rund um Nynäshamn zusammengestellt — Restaurants, Badestellen, Ausflugsziele und mehr. Bei Fragen oder Anregungen sind wir gerne für Sie da. ↗',

      // ── boat ──────────────────────────────────────────────────────
      'boat.back': '← Zurück zur Übersicht',
      'boat.eyebrow': 'Im Aufenthalt inbegriffen',
      'boat.hero.p': 'Ein kleines oranges Motorboot für sechs Personen mit einem 9,9-PS-Mercury-Motor — Ihr Tor zum Schärengarten. In Schweden ist für diesen Bootstyp kein Führerschein erforderlich.',
      'boat.stat1.label': 'Maximale Passagierzahl',
      'boat.stat2.label': 'Mercury-Außenbordmotor',
      'boat.stat3.val': 'Kein Führerschein',
      'boat.stat3.label': 'Nach schwedischem Recht',
      'boat.gs.h2': 'Erste Schritte',
      'boat.gs.sub': 'Grundlegende Einweisung erfolgt beim Check-in. Bitte beachten Sie Folgendes auf dem Wasser.',
      'boat.op.h3': 'Das Boot bedienen',
      'boat.op1': 'Der Betrieb des Bootes erfordert Erfahrung im Bootfahren und Kenntnisse der Seefahrtsregeln.',
      'boat.op2': 'Der Schärengarten hat flache Stellen und verborgene Unterwasserfelsen — bitte immer eine Navigations-App verwenden. Wir empfehlen <strong class="font-semibold text-stone-800">Skippo</strong>, das für den Grundgebrauch kostenlos ist.',
      'boat.op3': 'Bitte Geschwindigkeitsbegrenzungen und die ausgewiesenen Fahrtgebiete einhalten.',
      'boat.au.h3': 'Nach der Nutzung',
      'boat.au1': 'Das Boot nach der Nutzung an seinen Ursprungsort zurückbringen und sicher festbinden.',
      'boat.au2': 'Prüfen Sie, ob alle Schwimmwesten und Ausrüstungsgegenstände vorhanden und verstaut sind.',
      'boat.au3': 'Schäden oder Probleme bitte sofort melden.',
      'boat.safe.h2': 'Sicherheitsregeln',
      'boat.lj.h3': 'Schwimmwesten — Pflicht',
      'boat.lj.p': 'Alle Personen an Bord müssen jederzeit eine Schwimmweste tragen. Die Schwimmwesten befinden sich in der Aufbewahrungsbox am Steg.',
      'boat.child.h3': 'Kinder',
      'boat.child.p': 'Kinder müssen jederzeit von einem Erwachsenen beaufsichtigt werden.',
      'boat.alc.h3': 'Alkohol &amp; Drogen',
      'boat.alc.p': 'Das Führen des Bootes unter dem Einfluss von Alkohol oder Drogen ist nach schwedischem Seerecht verboten.',
      'boat.fuel.h2': 'Kraftstoffrichtlinie',
      'boat.tanks.h3': 'Tanks',
      'boat.tank1': '25-Liter-Innentank — wird <strong class="text-stone-800">vollgetankt</strong> bereitgestellt.',
      'boat.tank2': '5-Liter-Reservekanister an Bord.',
      'boat.tank3': 'Bei Bedarf wird zusätzlicher Kraftstoff bereitgestellt.',
      'boat.refuel.h3': 'Tanken',
      'boat.refuel.p': 'Das Boot muss <strong class="text-stone-800">vollgetankt</strong> zurückgegeben werden. Kraftstoff kostet <strong class="text-stone-800">2,50 € pro Liter</strong>, zahlbar per:',
      'boat.pay1': 'PayPal',
      'boat.pay2': 'Revolut',
      'boat.pay3': 'Banküberweisung',
      'boat.refuel.note': 'Schäden durch unsachgemäßes Betanken oder falschen Kraftstoff gehen zu Lasten des Gastes.',
      'boat.up.eyebrow': 'Optionales Upgrade',
      'boat.up.h3': 'Mehr Power gewünscht?',
      'boat.up.p': 'Finnmaster 4900CTX · 50 PS · 27–30 Knoten · GPS-Kartenplotter',
      'boat.up.btn': 'Upgrades ansehen →',

      // ── upgrades ──────────────────────────────────────────────────
      'up.back': '← Zurück zur Übersicht',
      'up.eyebrow': 'Optionale Zusatzleistungen',
      'up.h1': 'Upgrades',
      'up.hero.p': 'Heben Sie Ihren Aufenthalt auf das nächste Level — ein Premium-Motorboot oder Kajaks, um den Schärengarten auf eigene Faust zu erkunden.',
      'up.fm.badge': 'Premium-Upgrade',
      'up.fm.h2': 'Finnmaster 4900CTX',
      'up.fm.p': 'Eine deutliche Steigerung gegenüber der Tangerine Dream — für Inseltouren, Angelausflüge und Tagestouren auf Hochtouren.',
      'up.fm.s1.label': 'Selva-Motor · Normalbenzin 95',
      'up.fm.s2.label': 'Höchstgeschwindigkeit',
      'up.fm.s3.label': 'Länge · bis 6 Personen',
      'up.fm.s4.label': 'Kartenplotter inklusive',
      'up.fm.inc.h3': 'Im Lieferumfang enthalten',
      'up.fm.i1': 'Deep-V-Rumpf — ruhig auch bei Wellengang',
      'up.fm.i2': 'Elektrische Zündung mit Sicherheits-Killschalter',
      'up.fm.i3': 'Staufächer &amp; Badeleiter',
      'up.fm.i4': 'Gepolsterte Sitzplätze für 6 Personen',
      'up.fm.i5': 'Schwimmwesten (alle Größen)',
      'up.fm.i6': 'Paddel, Anker &amp; 25-Liter-Kraftstofftank',
      'up.fm.i7': 'Vollständige Sicherheitseinweisung',
      'up.fm.note': '<strong class="text-stone-700">Ideal für:</strong> Inseltouren, Einkaufsfahrten, Badebuchten, Angeln und Tagesausflüge.',
      'up.fm.price.h3': 'Preise',
      'up.kayak.h2': 'Kajakverleih',
      'up.kayak.p': 'Zwei Seabird-Discovery-Kajaks — leicht, stabil und ideal, um die Küste in Ihrem eigenen Tempo zu erkunden.',
      'up.kayak.inc.h3': 'Im Lieferumfang enthalten',
      'up.kayak.i1': 'Schwimmwesten',
      'up.kayak.i2': 'Paddel',
      'up.kayak.i3': 'Spritzschutz',
      'up.kayak.i4': 'Für alle Erfahrungsstufen geeignet',
      'up.kayak.res': 'Vorabkontakt empfohlen — kontaktieren Sie uns zum Buchen.',
      'up.kayak.price.h3': 'Preise',
      'up.kayak.p1.name': 'Einzelkajak',
      'up.kayak.p1.sub': 'Pro Woche',
      'up.kayak.p2.name': 'Beide Kajaks',
      'up.kayak.p2.sub': 'Pro Woche · Bestes Preis-Leistungs-Verhältnis',
    }
  };

  function apply(lang) {
    document.querySelectorAll('[data-i18n]').forEach(function (el) {
      var key = el.getAttribute('data-i18n');
      if (T[lang] && T[lang][key] !== undefined) {
        el.innerHTML = T[lang][key];
      }
    });
    ['en', 'de'].forEach(function (l) {
      var btn = document.getElementById('lang-' + l);
      if (!btn) return;
      btn.classList.toggle('bg-emerald-700', l === lang);
      btn.classList.toggle('text-white', l === lang);
      btn.classList.toggle('text-emerald-400', l !== lang);
    });
    try { localStorage.setItem('lang', lang); } catch (e) {}
  }

  window.setLang = apply;

  document.addEventListener('DOMContentLoaded', function () {
    var saved = 'en';
    try { saved = localStorage.getItem('lang') || 'en'; } catch (e) {}
    apply(saved);
  });
})();
